#!/bin/sh

### BEGIN INIT INFO
# Provides:          {{ service_name }}
# Required-Start:    $local_fs $remote_fs $network $syslog $docker
# Required-Stop:     $local_fs $remote_fs $network $syslog $docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts a nginx-proxy container
# Description:       starts a nginx-proxy container
### END INIT INFO

IMAGE_NAME="{{ image_name }}"
CONTAINER_NAME="{{ container_name }}"

start() {
docker run -d \
-p 80:80 -p 443:443 \
-v /var/run/docker.sock:/tmp/docker.sock \
-v /etc/${CONTAINER_NAME}/certs:/etc/nginx/certs \
--name ${CONTAINER_NAME} -t \
${IMAGE_NAME}
}

stop() {
docker rm -f ${CONTAINER_NAME}
}


case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac


